
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- OFERTAS CATÁLOGO 17 (2025) ---
    {
        id: 41070,
        name: "Contorno de Ojos y Labios Renewing Restore Novage+",
        brand: "Novage+",
        price: 13.08,
        regularPrice: 38.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41070%2F41070_1.png",
        description: "Contorno de ojos y labios avanzado que restaura la piel, reduce arrugas y mejora la elasticidad.",
        stock: 50,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 504
    },
    {
        id: 44098,
        name: "Tratamiento de Día SPF 30 Multi-Correcting Restore Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44098%2F44098_1.png",
        description: "Crema de día multi-correctora con SPF 30. Combate los signos del envejecimiento y protege la piel.",
        stock: 60,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 839
    },
    {
        id: 47514,
        name: "Eau de Parfum Miss Giordani Floral",
        brand: "Giordani Gold",
        price: 13.85,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47514%2F47514_1.png",
        description: "Un aroma floral sofisticado y vibrante para celebrar momentos especiales. La elegancia hecha perfume.",
        stock: 80,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 753
    },
    {
        id: 47502,
        name: "Eau de Parfum Mister Giordani Aqua",
        brand: "Giordani Gold",
        price: 14.62,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47502%2F47502_1.png",
        description: "Fragancia acuática y refinada para el hombre moderno. Una escapada a la costa italiana.",
        stock: 0, // 'De vuelta muy pronto'
        category: "men",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 516
    },
    {
        id: 47499,
        name: "Eau de Toilette Elvie Midnight Magic",
        brand: "Elvie",
        price: 13.85,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47499%2F47499_1.png",
        description: "Magia de medianoche en una botella. Aroma misterioso y encantador para noches inolvidables.",
        stock: 45,
        category: "perfume",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 528
    },
    {
        id: 46805,
        name: "Bruma Corporal Perfumada Amber Elixir Warm Temptation",
        brand: "Amber Elixir",
        price: 7.69,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46805%2F46805_1.png",
        description: "Seductora bruma corporal con notas cálidas de ámbar. Ideal para llevar siempre contigo.",
        stock: 100,
        category: "perfume",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 718
    },
    {
        id: 46806,
        name: "Bruma Corporal Perfumada Possess Mythical Seduction",
        brand: "Possess",
        price: 9.23,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46806%2F46806_1.png",
        description: "Bruma seductora inspirada en la leyenda de Cleopatra. Notas intensas y misteriosas.",
        stock: 90,
        category: "perfume",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 765
    },
    {
        id: 46807,
        name: "Bruma Corporal Perfumada Giordani Gold Everlasting Glow",
        brand: "Giordani Gold",
        price: 9.23,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46807%2F46807_1.png",
        description: "El resplandor dorado de Giordani Gold en una bruma ligera y sofisticada.",
        stock: 85,
        category: "perfume",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 928
    },
    {
        id: 46793,
        name: "Eau de Toilette Every Me Sweetheart Rose",
        brand: "Every Me",
        price: 14.62,
        regularPrice: 43.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46793%2F46793_1.png",
        description: "Una fragancia dulce y romántica con notas de rosa para el día a día.",
        stock: 60,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 231
    },

    // --- NUEVOS PRODUCTOS MAQUILLAJE & ACCESORIOS (Desde HTML proporcionado) ---
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "Iluminador líquido versátil para un brillo natural o intenso. Mezclable y modulable.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.2,
        reviewCount: 5
    },
    {
        id: 46137,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46137%2F46137_1.png",
        description: "BB Cream multifuncional que hidrata, corrige y protege. Acabado natural.",
        stock: 60,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 289,
        variants: {
            "Tono": [
                { value: "Fair", colorCode: "#F3D8C8" },
                { value: "Light", colorCode: "#EBC9B4" },
                { value: "Medium", colorCode: "#D8AD94" },
                { value: "Dark", colorCode: "#B68266" }
            ]
        }
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 16.93,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas bronceadoras infusionadas con serum antiedad. Edición limitada.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 82
    },
    {
        id: 46941,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46941%2F46941_1.png",
        description: "Iluminador en barra fácil de aplicar para un brillo radiante al instante.",
        stock: 80,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 552
    },
    {
        id: 46913,
        name: "Maquillaje Stress-Free Everlasting Sync SPF 20 + Protección UVA Natural THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46913%2F46913_1.png",
        description: "Base de maquillaje inteligente que se adapta a tu piel y al entorno.",
        stock: 75,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 1038,
        variants: {
            "Tono": [
                { value: "Alabaster", colorCode: "#F7E6D9" },
                { value: "Porcelain", colorCode: "#F1D9C8" },
                { value: "Ivory", colorCode: "#EDD0BE" },
                { value: "Beige", colorCode: "#E2C0A8" }
            ]
        }
    },
    {
        id: 42121,
        name: "Paleta de Ojos y Rostro Fabulous Beauty Giordani Gold",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png",
        description: "Paleta todo en uno de lujo para ojos y rostro. Pigmentación intensa y sedosa.",
        stock: 40,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 371
    },
    {
        id: 42105,
        name: "Maquillaje Mineral de Larga Duración SPF 20 Giordani Gold",
        brand: "Giordani Gold",
        price: 13.08,
        regularPrice: 31.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42105%2F42105_1.png",
        description: "Base mineral de larga duración con cobertura completa y acabado luminoso.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1066
    },
    {
        id: 41108,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 8.46,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41108%2FES%2F41108_1.png",
        description: "Corrector que borra imperfecciones mientras trata la piel con su serum.",
        stock: 50,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1053
    },
    {
        id: 43245,
        name: "Maquillaje Eternal Glow SPF 25 Giordani Gold",
        brand: "Giordani Gold",
        price: 16.16,
        regularPrice: 32.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43245%2FES%2F43245_1.png",
        description: "Base fluida que aporta una luminosidad eterna y rejuvenece la piel.",
        stock: 55,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1020
    },
    {
        id: 44834,
        name: "Polvos Compactos con Serum Giordani Gold",
        brand: "Giordani Gold",
        price: 13.08,
        regularPrice: 26.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44834%2F44834_1.png",
        description: "Polvos compactos sedosos enriquecidos con serum para un acabado impecable.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 369
    },
    {
        id: 34647,
        name: "Polvos Compactos Everlasting THE ONE",
        brand: "The ONE",
        price: 9.23,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34647%2F34647_1.png",
        description: "Polvos de larga duración que matifican y fijan el maquillaje durante horas.",
        stock: 70,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 327
    },
    {
        id: 46934,
        name: "Polvos Bronceadores Giordani Gold Essenza",
        brand: "Giordani Gold",
        price: 18.47,
        regularPrice: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46934%2F46934_1.png",
        description: "Bronceado natural y lujoso con el aroma icónico de Essenza.",
        stock: 45,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 388
    },
    {
        id: 46931,
        name: "Tinte Bronceador Giordani Gold Essenza",
        brand: "Giordani Gold",
        price: 12.31,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46931%2F46931_1.png",
        description: "Tinte ligero que aporta un color bronceado saludable y natural.",
        stock: 50,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 346
    },
    {
        id: 42236,
        name: "Maquillaje Antienvejecimiento Serum Boost SPF 12 + Protección UVA Giordani Gold",
        brand: "Giordani Gold",
        price: 23.87,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42236%2F42236_1.png",
        description: "Base antiedad que mejora la firmeza y elasticidad de la piel.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1558
    },
    {
        id: 46329,
        name: "Maquillaje Illuskin Glow Reflective THE ONE",
        brand: "The ONE",
        price: 15.40,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46329%2F46329_1.png",
        description: "Piel radiante y luminosa con tecnología reflectante de luz.",
        stock: 70,
        category: "makeup",
        rating: 4.7,
        reviewCount: 614
    },
    {
        id: 42610,
        name: "Limpiadora Micelar Calmante Optimals",
        brand: "Optimals",
        price: 8.46,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42610%2F42610_1.png",
        description: "Limpia y calma la piel suavemente. Ideal para desmaquillar.",
        stock: 90,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 968
    },
    {
        id: 44547,
        name: "Prebase On Screen Finish Make-up Pro THE ONE",
        brand: "The ONE",
        price: 6.54,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44547%2F44547_1.png",
        description: "Prepara tu piel para un maquillaje duradero y perfecto en cámara.",
        stock: 65,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 443
    },
    {
        id: 36133,
        name: "Iluminador Líquido Illuskin The ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36133%2F36133_1.png",
        description: "Gotas iluminadoras para resaltar tus facciones con un brillo sutil.",
        stock: 55,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 456
    },
    {
        id: 32922,
        name: "Maquillaje Liquid Silk Giordani Gold",
        brand: "Giordani Gold",
        price: 23.87,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F32922%2FES%2F32922_1.png",
        description: "Textura sedosa ultraligera que perfecciona la tez con un acabado natural.",
        stock: 50,
        category: "makeup",
        rating: 4.8,
        reviewCount: 2055
    },
    {
        id: 42118,
        name: "Prebase y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 20.79,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42118%2FES%2F42118_1.png",
        description: "Prebase lujosa que hidrata, ilumina y prolonga la duración del maquillaje.",
        stock: 10,
        category: "makeup",
        tag: "ULTIMAS UNIDADES",
        rating: 4.9,
        reviewCount: 1554
    },
    {
        id: 35640,
        name: "Bálsamo BB Cream OnColour",
        brand: "OnColour",
        price: 7.70,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F35640%2F35640_1.png",
        description: "BB Cream ligera que unifica el tono e hidrata la piel.",
        stock: 80,
        category: "makeup",
        rating: 4.8,
        reviewCount: 746
    },
    {
        id: 42112,
        name: "Crema Correctora del Color SPF 30 + Protección UVA Giordani Gold",
        brand: "Giordani Gold",
        price: 23.10,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42112%2F42112_1.png",
        description: "CC Cream que corrige el color, protege e hidrata. Cobertura media.",
        stock: 60,
        category: "makeup",
        rating: 4.8,
        reviewCount: 386
    },
    {
        id: 41989,
        name: "Corrector Everlasting Sync THE ONE",
        brand: "The ONE",
        price: 12.32,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41989%2F41989_1.png",
        description: "Corrector de alta cobertura que se sincroniza con las necesidades de tu piel.",
        stock: 70,
        category: "makeup",
        rating: 4.6,
        reviewCount: 1106
    },
    {
        id: 21339,
        name: "Solución Micelar Diamond Cellular",
        brand: "Diamond Cellular",
        price: 12.31,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F21339%2FES%2F21339_1.png",
        description: "Limpiadora 3 en 1 de lujo: limpia, tonifica y desmaquilla.",
        stock: 80,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1865
    },
    {
        id: 44915,
        name: "Perlas con Serum Giordani Gold",
        brand: "Giordani Gold",
        price: 26.95,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44915%2F44915_1.png",
        description: "Las clásicas perlas bronceadoras ahora con serum hialurónico.",
        stock: 60,
        category: "makeup",
        rating: 4.8,
        reviewCount: 1554
    },
    {
        id: 42127,
        name: "Maquillaje Semi-Mate Everlasting Sync SPF 10 + Protección UVA THE ONE",
        brand: "The ONE",
        price: 15.40,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42127%2F42127_1.png",
        description: "Base semi-mate resistente a la transferencia y al sudor.",
        stock: 65,
        category: "makeup",
        rating: 4.6,
        reviewCount: 648
    },
    {
        id: 39292,
        name: "Crema Iluminadora Peach OnColour",
        brand: "OnColour",
        price: 8.47,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F39292%2F39292_1.png",
        description: "Crema hidratante con tinte melocotón para un brillo saludable.",
        stock: 75,
        category: "makeup",
        rating: 4.8,
        reviewCount: 585
    },
    {
        id: 43416,
        name: "Polvos Sueltos Make-up Pro THE ONE",
        brand: "The ONE",
        price: 13.09,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43416%2F43416_1.png",
        description: "Polvos sueltos ultra-finos para fijar el maquillaje y controlar brillos.",
        stock: 55,
        category: "makeup",
        rating: 4.6,
        reviewCount: 493
    },
    {
        id: 41750,
        name: "Bálsamo BB Cream Matte SPF 10 OnColour",
        brand: "OnColour",
        price: 3.07,
        regularPrice: 10.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41750%2F41750_1.png",
        description: "BB Cream efecto mate para pieles mixtas y grasas.",
        stock: 80,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 375
    },
    {
        id: 36141,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36141%2FES%2F36141_1.png",
        description: "Iluminador en barra práctico para un toque de luz rápido.",
        stock: 45,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.6,
        reviewCount: 154
    },
    {
        id: 40830,
        name: "Maquillaje Aquaboost Illuskin SPF 20 THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 23.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40830%2F40830_1.png",
        description: "Base hidratante con agua de glaciar para una piel fresca y radiante.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.5,
        reviewCount: 195
    },
    {
        id: 47529,
        name: "Discos de Algodón Reutilizables",
        brand: "Oriflame",
        price: 7.70,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47529%2F47529_1.png",
        description: "Discos desmaquillantes lavables y ecológicos. Pack de 10.",
        stock: 100,
        category: "accessories",
        rating: 4.8,
        reviewCount: 72
    },
    {
        id: 47520,
        name: "Rodillo Volcánico Matificante",
        brand: "Oriflame",
        price: 10.01,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47520%2F47520_1.png",
        description: "Elimina el exceso de grasa al instante sin arruinar el maquillaje.",
        stock: 40,
        category: "accessories",
        rating: 4.6,
        reviewCount: 123
    },
    {
        id: 42483,
        name: "Pincel para Corrector THE ONE",
        brand: "The ONE",
        price: 2.53,
        regularPrice: 8.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42483%2F42483_1.png",
        description: "Pincel de precisión para aplicar corrector y cubrir imperfecciones.",
        stock: 90,
        category: "accessories",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 90
    },

    // --- PRODUCTOS ANTERIORES (Manteniendo catálogo base) ---
    {
        id: 29696,
        name: "WellnessPack Mujer",
        brand: "Wellness by Oriflame",
        price: 32.99,
        regularPrice: 46.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F29696%2F29696.png",
        description: "Suplemento diario todo en 1 con multivitaminas, minerales, omega 3 y astaxantina.",
        stock: 50,
        category: "wellness",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1250,
        beautyPoints: 33
    },
    {
        id: 29697,
        name: "WellnessPack Hombre",
        brand: "Wellness by Oriflame",
        price: 32.99,
        regularPrice: 46.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F29697%2F29697_1.png",
        description: "Salud óptima para él en un cómodo sobre diario. Vitaminas, minerales y antioxidantes.",
        stock: 45,
        category: "wellness",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 980,
        beautyPoints: 33
    },
    {
        id: 38531,
        name: "Giordani Gold Essenza Blossom Parfum",
        brand: "Giordani Gold",
        price: 24.99,
        regularPrice: 66.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38531%2F38531_1.png",
        description: "Una joya de la perfumería. Aroma floral blanco con Camelia Celebratissima y Azahar.",
        stock: 100,
        category: "perfume",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 412,
    },
    {
        id: 42503,
        name: "Limpiador en Gel NovAge Supreme",
        brand: "NovAge",
        price: 19.99,
        regularPrice: 34.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F33984%2F33984_1.png",
        description: "Limpieza inteligente que preserva la barrera cutánea. Limpia y tonifica en un solo paso.",
        stock: 60,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.7,
        reviewCount: 890,
    },
    {
        id: 44961,
        name: "Acondicionador Rico Reparador Duologi",
        brand: "DUOLOGI",
        price: 7.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44961%2F44961_1.png",
        description: "Acondicionador nutritivo que repara y protege el cabello dañado reduciendo la rotura.",
        howToUse: "Aplicar sobre el cabello húmedo de medios a puntas. Dejar actuar y aclarar.",
        stock: 100,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 55,
    },
    {
        id: 44960,
        name: "Acondicionador Ligero Voluminizador DUOLOGI",
        brand: "DUOLOGI",
        price: 7.99,
        regularPrice: 16.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44960%2F44960_1.png",
        description: "Acondicionador ligero que hidrata y desenreda cabellos finos sin apelmazar.",
        stock: 85,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.6,
        reviewCount: 42,
    },
    {
        id: 47440,
        name: "Gel de Ducha con Fresa Orgánica Simple Joys Love Nature",
        brand: "Love Nature",
        price: 2.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47440%2F47440_1.png',
        description: "Edición Especial. Gel de ducha refrescante con delicioso aroma a fresa orgánica.",
        stock: 80,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 202,
    },
    {
        id: 46987,
        name: "Gel de Ducha con Mango Orgánico Simple Joys Love Nature",
        brand: "Love Nature",
        price: 6.99,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46987%2F46987_1.png',
        description: "Gel de ducha con extracto de mango orgánico, suave y afrutado.",
        stock: 75,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 731,
    },
    {
        id: 41338,
        name: "Crema de Manos Nutritiva con Aceite de Coco Orgánico",
        brand: "Love Nature",
        price: 2.99,
        regularPrice: 11.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41338%2FES%2F41338_1.png',
        description: "Nutrición intensa para manos secas con las propiedades del coco.",
        stock: 50,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 700,
    },
    {
        id: 36151,
        name: "Crema Universal con Aceite de Grosella Negra",
        brand: "Tender Care",
        price: 3.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F36151%2F36151_1.png',
        description: "El bálsamo clásico con un toque afrutado de grosella negra.",
        stock: 100,
        category: 'skincare',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 2226,
    },
    {
        id: 38601,
        name: "Aceite Protección Capilar Eleo",
        brand: "Eleo",
        price: 21.99,
        regularPrice: 26.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38601%2F38601_1.png',
        description: "Aceite lujoso con Argán y Rosas para proteger y nutrir el cabello.",
        stock: 30,
        category: 'hair',
        rating: 4.8,
        reviewCount: 921,
    },
    {
        id: 46968,
        name: "Crema para Manos y Cuerpo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 19.00,
        regularPrice: 24.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png',
        description: "La legendaria crema nutritiva con extractos orgánicos de leche y miel.",
        stock: 80,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 3560,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 29.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica y duradera.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 38497,
        name: "Divine Eau de Parfum",
        brand: "Divine",
        price: 26.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "Fragancia icónica con notas de Orquídea y Almizcle. Elegancia en estado puro.",
        stock: 40,
        category: 'perfume',
        rating: 4.9,
        reviewCount: 340
    },
    {
        id: 30468,
        name: "Be The Legend Eau de Toilette",
        brand: "Be The Legend",
        price: 24.99,
        regularPrice: 38.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F30468%2F30468_1.png",
        description: "Para el hombre seguro de sí mismo. Notas de cuero, manzana y haba tonka.",
        stock: 35,
        category: "men",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 512
    },
    {
        id: 46642,
        name: "Jabón Líquido Manos y Cuerpo Limón y Verbena Essense & Co",
        brand: "Essense&Co.",
        price: 15.99,
        regularPrice: 20.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46642%2F46642_1.png',
        description: "Elegante jabón líquido con aceites naturales de limón y verbena.",
        stock: 30,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1139,
    },
    {
        id: 41308,
        name: "Tratamiento Hot Oil para Cabello Seco con Trigo y Coco",
        brand: "Love Nature",
        price: 2.49,
        regularPrice: 6.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41308%2FES%2F41308_1.png',
        description: "Tratamiento intensivo de aceite caliente para nutrir el cabello seco.",
        stock: 100,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 615,
    },
    {
        id: 47878,
        name: "Esponja de Baño Lather Lily",
        brand: "Love Nature",
        price: 3.99,
        regularPrice: 9.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47878%2F47878_1.png",
        description: "Esponja de baño que genera abundante espuma para una ducha placentera.",
        stock: 50,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.6,
        reviewCount: 209,
    },
    {
        id: 47677,
        name: "Cepillo Estilizador Glam On-the-Go",
        brand: "StylerPRO",
        price: 64.99,
        regularPrice: 80.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47677%2F47677_1.png",
        description: "Cepillo alisador compacto para retocar tu peinado en cualquier lugar. ¡Novedad!",
        stock: 15,
        category: 'hair',
        tag: 'NOVEDAD',
        rating: 4.7,
        reviewCount: 70,
    }
];
