
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- MAQUILLAJE & NOVEDADES (Desde tu HTML) ---
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "Iluminador líquido versátil para un brillo natural o intenso. Mezclable y modulable.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.2,
        reviewCount: 5
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15 THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png",
        description: "BB Cream multifuncional que hidrata, corrige y protege. Acabado natural.",
        stock: 289,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 289,
        variants: {
            "Tono": [
                { value: "Fair", colorCode: "#F3D8C8" },
                { value: "Light", colorCode: "#EBC9B4" },
                { value: "Medium", colorCode: "#D8AD94" },
                { value: "Dark", colorCode: "#B68266" }
            ]
        }
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 16.93,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas bronceadoras infusionadas con serum antiedad. Edición limitada.",
        stock: 50,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 82
    },
    {
        id: 46940,
        name: "Stick Iluminador con Color THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46940%2F46940_1.png",
        description: "Iluminador en barra fácil de aplicar para un brillo radiante al instante.",
        stock: 80,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 552,
        variants: {
            "Tono": [
                { value: "Hot Pink", colorCode: "#E88DA3" },
                { value: "Coral", colorCode: "#EE9D8A" },
                { value: "Bronze", colorCode: "#C68E73" },
                { value: "Champagne", colorCode: "#F2D8C6" }
            ]
        }
    },
    {
        id: 46906,
        name: "Maquillaje Stress-Free Everlasting Sync SPF 20 + Protección UVA Natural THE ONE",
        brand: "The ONE",
        price: 8.46,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46906%2F46906_1.png",
        description: "Base de maquillaje inteligente que se adapta a tu piel y al entorno.",
        stock: 75,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 1038,
        variants: {
            "Tono": [
                { value: "Alabaster", colorCode: "#F7E6D9" },
                { value: "Porcelain", colorCode: "#F1D9C8" },
                { value: "Ivory", colorCode: "#EDD0BE" },
                { value: "Beige", colorCode: "#E2C0A8" },
                { value: "Sun", colorCode: "#D9A683" },
                { value: "Amber", colorCode: "#C8926F" }
            ]
        }
    },
    {
        id: 42121,
        name: "Paleta de Ojos y Rostro Fabulous Beauty Giordani Gold",
        brand: "Giordani Gold",
        price: 19.24,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42121%2F42121_1.png",
        description: "Paleta todo en uno de lujo para ojos y rostro. Pigmentación intensa y sedosa.",
        stock: 40,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 371
    },
    {
        id: 42102,
        name: "Maquillaje Mineral de Larga Duración SPF 20 Giordani Gold",
        brand: "Giordani Gold",
        price: 13.08,
        regularPrice: 31.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42102%2F42102_1.png",
        description: "Base mineral de larga duración con cobertura completa y acabado luminoso.",
        stock: 60,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1066,
        variants: {
            "Tono": [
                { value: "Light Rose", colorCode: "#F3D3C6" },
                { value: "Light Ivory", colorCode: "#EFCEBF" },
                { value: "Rose Beige", colorCode: "#E6BCA9" },
                { value: "Natural Beige", colorCode: "#E2B5A2" }
            ]
        }
    },
    {
        id: 41107,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 8.46,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41107%2FES%2F41107_1.png",
        description: "Corrector que borra imperfecciones mientras trata la piel con su serum.",
        stock: 50,
        category: "makeup",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1053,
        variants: {
            "Tono": [
                { value: "Light", colorCode: "#F1D5C5" },
                { value: "Medium", colorCode: "#E2BC9F" }
            ]
        }
    },

    // --- CUIDADO DE LA PIEL & NOVAGE+ (Segundo bloque HTML) ---
    {
        id: 47847,
        name: "Lote Ritual de Cuidado de la Piel Wellosophy",
        brand: "Wellosophy",
        price: 53.89,
        regularPrice: 101.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47847%2F47847_1.png",
        description: "Rutina completa para el bienestar de tu piel desde el interior y el exterior.",
        stock: 62,
        category: "wellness",
        tag: "SET",
        rating: 4.7,
        reviewCount: 62,
        beautyPoints: 50
    },
    {
        id: 47785,
        name: "Lote Antioxidante Wellosophy",
        brand: "Wellosophy",
        price: 102.41,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47785%2F47785_1.png",
        description: "Protección antioxidante avanzada para combatir los radicales libres.",
        stock: 16,
        category: "wellness",
        tag: "SET",
        rating: 4.7,
        reviewCount: 16,
        beautyPoints: 95
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Potenciador con Niacinamida para fortalecer la barrera cutánea y mejorar la textura.",
        stock: 160,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 160
    },
    {
        id: 48675,
        name: "Caja de Regalo Crema Universal - Edición Especial",
        brand: "Crema Universal",
        price: 13.85,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48675%2F48675_1.png",
        description: "Trío de cremas universales: Grosella Negra, Original y Ciruela Dulce.",
        stock: 100,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 2
    },
    {
        id: 48105,
        name: "Mascarilla Revitalizante Intensiva Acción Noche Novage+",
        brand: "Novage+",
        price: 20.78,
        regularPrice: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48105%2F48105_1.png",
        description: "Mascarilla nocturna intensiva para una piel revitalizada al despertar.",
        stock: 80,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 45
    },
    {
        id: 48117,
        name: "Crema de Noche Reafirmante Royal Velvet - Edición Especial",
        brand: "Royal Velvet",
        price: 18.47,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48117%2F48117_1.png",
        description: "Crema de noche rica en infusión de Iris Negro para reafirmar la piel madura.",
        stock: 55,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1250
    },
    {
        id: 48115,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 18.47,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48115%2F48115_1.png",
        description: "Crema de día reafirmante que hidrata y protege la piel.",
        stock: 12,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1300
    },
    {
        id: 48114,
        name: "Cápsulas Restauradoras con Aceites Naturales Novage+",
        brand: "Novage+",
        price: 32.33,
        regularPrice: 65.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48114%2F48114_1.png",
        description: "Mezcla de aceites preciosos en cápsulas monodosis para nutrir la piel.",
        stock: 8,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 668
    },
    {
        id: 48649,
        name: "Crema Universal Original - Edición Especial",
        brand: "Crema Universal",
        price: 5.38,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48649%2F48649_1.png",
        description: "La fórmula original icónica que suaviza y protege la piel seca.",
        stock: 727,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 5.0,
        reviewCount: 727
    },
    {
        id: 45147,
        name: "Serum Facial de Aceite Reafirmante y Relajante Wellosophy",
        brand: "Wellosophy",
        price: 26.95,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45147%2F45147_1.png",
        description: "Aceite facial ligero que reafirma y relaja la piel estresada.",
        stock: 142,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 142
    },
    {
        id: 45248,
        name: "Serum Even Out Optimals",
        brand: "Optimals",
        price: 13.85,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45248%2F45248_1.png",
        description: "Serum que reduce la apariencia de manchas oscuras y unifica el tono.",
        stock: 317,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 317
    },
    {
        id: 45245,
        name: "Crema Hidratante Rica Even Out Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45245%2F45245_1.png",
        description: "Hidratante rica que ayuda a prevenir manchas y nutre la piel.",
        stock: 222,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 222
    },
    {
        id: 47439,
        name: "Crema Universal con Ciruela Dulce",
        brand: "Crema Universal",
        price: 4.84,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47439%2F47439_1.png",
        description: "Edición limitada con delicioso aroma a ciruela dulce.",
        stock: 1618,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 1618
    },
    {
        id: 45291,
        name: "Contorno de Ojos y Labios Optimals",
        brand: "Optimals",
        price: 12.31,
        regularPrice: 24.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45291%2F45291_1.png",
        description: "Cuidado reafirmante para la delicada zona de ojos y labios.",
        stock: 436,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 436
    },
    {
        id: 44098,
        name: "Tratamiento de Día SPF 30 Multi-Correcting Restore Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44098%2F44098_1.png",
        description: "Crema de día multi-correctora con SPF 30. Combate los signos del envejecimiento.",
        stock: 839,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 839
    },
    {
        id: 44285,
        name: "Tratamiento de Noche Multi-Recover Restore Novage+",
        brand: "Novage+",
        price: 19.24,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44285%2F44285_1.png",
        description: "Crema de noche reparadora que activa la recuperación nocturna de la piel.",
        stock: 668,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 668
    },
    {
        id: 41075,
        name: "Serum Renewing Restore Novage+",
        brand: "Novage+",
        price: 29.25,
        regularPrice: 64.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41075%2F41075_1.png",
        description: "Serum renovador que mejora la elasticidad y reduce arrugas profundas.",
        stock: 664,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 664
    },
    {
        id: 41070,
        name: "Contorno de Ojos y Labios Renewing Restore Novage+",
        brand: "Novage+",
        price: 13.08,
        regularPrice: 38.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41070%2F41070_1.png",
        description: "Contorno de ojos avanzado para restaurar la firmeza.",
        stock: 504,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 504
    },
    {
        id: 45292,
        name: "Multi-Protector SPF 50 Daily Glow Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45292%2F45292_1.png",
        description: "Protección solar alta con acabado luminoso para uso diario.",
        stock: 738,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 738
    },
    {
        id: 45243,
        name: "Crema Hidratante Ligera Even Out Optimals",
        brand: "Optimals",
        price: 10.00,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45243%2F45243_1.png",
        description: "Hidratante ligera que unifica el tono y matifica la piel.",
        stock: 204,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 204
    },
    {
        id: 46989,
        name: "Crema Universal con Mandarina Dulce",
        brand: "Crema Universal",
        price: 5.38,
        regularPrice: 14.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46989%2FES%2F46989_1.png",
        description: "Edición especial con extracto de mandarina. Suaviza y protege.",
        stock: 2295,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 2295
    },
    {
        id: 41059,
        name: "Fluido Ultraligero Alta Protección SPF 50 Proceuticals Novage+",
        brand: "Novage+",
        price: 16.16,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41059%2F41059_1.png",
        description: "Escudo protector invisible contra rayos UVA/UVB y contaminación.",
        stock: 1888,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 1888
    },
    {
        id: 41032,
        name: "Limpiadora Oleosa Comfort Novage+",
        brand: "Novage+",
        price: 16.93,
        regularPrice: 30.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41032%2F41032_1.png",
        description: "Limpiadora en aceite que disuelve el maquillaje y las impurezas al instante.",
        stock: 510,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 510
    },
    {
        id: 47437,
        name: "Parches Faciales de Gel Hydra-Glow Optimals",
        brand: "Optimals",
        price: 4.23,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47437%2F47437_1.png",
        description: "Parches refrescantes para hidratar y revitalizar la zona de los ojos.",
        stock: 0,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.7,
        reviewCount: 196
    },
    {
        id: 34849,
        name: "Aceite Purificante con Árbol de Té y Lima Love Nature",
        brand: "Love Nature",
        price: 6.54,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34849%2F34849_1.png",
        description: "Aceite concentrado para combatir imperfecciones y purificar la piel.",
        stock: 1783,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 1783
    },
    {
        id: 41037,
        name: "Serum Lift + Firm Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41037%2F41037_1.png",
        description: "Serum lifting que redefine el óvalo facial y mejora la firmeza.",
        stock: 583,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 583
    },
    {
        id: 47102,
        name: "Retinol Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 23.09,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47102%2F47102_1.png",
        description: "Tratamiento intensivo con Retinol encapsulado para reducir arrugas.",
        stock: 421,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 421
    },
    {
        id: 40670,
        name: "Prebase Perfeccionadora Woke Up Like This Waunt",
        brand: "Waunt",
        price: 13.85,
        regularPrice: 27.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40670%2FES%2F40670_1.png",
        description: "Prebase híbrida que ilumina y perfecciona la piel al instante.",
        stock: 418,
        category: "makeup",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 418
    },
    {
        id: 41035,
        name: "Serum Wrinkle Smooth Novage+",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41035%2F41035_1.png",
        description: "Serum antiarrugas avanzado que suaviza la textura de la piel.",
        stock: 395,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 395
    },
    {
        id: 41040,
        name: "Serum Bright Intense",
        brand: "Novage+",
        price: 26.94,
        regularPrice: 58.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41040%2F41040_1.png",
        description: "Serum iluminador que reduce manchas y mejora la luminosidad.",
        stock: 338,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 338
    },
    {
        id: 48678,
        name: "Parches Exfoliantes y Limpiadores Proceuticals Novage+",
        brand: "Novage+",
        price: 3.84,
        regularPrice: 9.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48678%2F48678_1.png",
        description: "Discos exfoliantes de doble cara para una piel suave y radiante.",
        stock: 271,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.8,
        reviewCount: 271
    },
    {
        id: 45326,
        name: "Crema Hidratante SPF 25 The Beyond Optimals",
        brand: "Optimals",
        price: 18.47,
        regularPrice: 36.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F45326%2F45326_1.png",
        description: "Hidratante diaria con protección SPF 25 para todo tipo de pieles.",
        stock: 358,
        category: "skincare",
        tag: "NOVEDAD",
        rating: 4.9,
        reviewCount: 358
    },
    {
        id: 46900,
        name: "Limpiador Soft Creamy Optimals",
        brand: "Optimals",
        price: 8.46,
        regularPrice: 19.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46900%2F46900_1.png",
        description: "Limpiadora en crema suave que elimina impurezas sin resecar.",
        stock: 576,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 576
    },
    {
        id: 46992,
        name: "Mascarilla Facial Iluminadora Gel to Ice con Mango Orgánico Love Nature",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46992%2F46992_1.png",
        description: "Mascarilla refrescante de mango para una piel radiante.",
        stock: 468,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.9,
        reviewCount: 468
    },
    {
        id: 46990,
        name: "Mascarilla Facial Hidratante Gel to Ice con Sandía Orgánica Love Nature",
        brand: "Love Nature",
        price: 2.30,
        regularPrice: 6.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46990%2F46990_1.png",
        description: "Mascarilla hidratante de sandía. Úsala fría para un efecto calmante.",
        stock: 567,
        category: "skincare",
        tag: "OFERTA",
        rating: 4.8,
        reviewCount: 567
    }
];
